app_id: xxxx
app_hash: xxxx
session_file: ./session/session
watch_channel_id_list:
  - xxxx
super_channel_id_list:
  - xxxx
log:
  level: info
  debug: true
download_pool: 1000
max_file_size: 1024
download_dir: ./downloads
watch_file_key_word:
  - cos
phone: +xxxxxx