app_id: 19967693
app_hash: d2f7c6927d7ab92ee20e978ea88bb682
session_file: ./session/session
watch_channel_id_list:
  - 1549179925
  - 1778419548
log:
  level: info
  debug: true
download_pool: 1000
download_dir: ./downloads
watch_file_key_word:
  - 福利姬
phone: +8618612345678