app_id: xxxxxx
app_hash: xxxxxx
session_file: ./session/session
watch_channel_id_list:
  - 1549179925
  - 1778419548
log:
  level: info
  debug: true
download_pool: 1000
download_dir: ./downloads
watch_file_key_word:
  - 学习
phone: +8618612345678