name: Docker

on:
  push:
    # 每次 push tag 时进行构建，不需要每次 push 都构建。使用通配符匹配每次 tag 的提交，记得 tag 名一定要以 v 开头
    tags:
      - v*

env:
  # 设置 docker 镜像名
  IMAGE_NAME: d-telegram

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -f api/update/Dockerfile -t $IMAGE_NAME .

      - name: Login to registry
        run: echo "${{ secrets.DOCKER_USER_PASS }}" | docker login -u ${{ secrets.DOCKER_USER_NAME }} --password-stdin

      - name: Push image
        run: |
          # 从 GitHub.ref 中取出版本
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # 从 tag 名字中替换 v 字符
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # 设置镜像 id 和版本号
          docker tag $IMAGE_NAME ${{ secrets.DOCKER_USER_NAME }}/$IMAGE_NAME:$VERSION
          # 进行 push
          docker push ${{ secrets.DOCKER_USER_NAME }}/$IMAGE_NAME:$VERSION